"""empty message

Revision ID: 140b24629ef4
Revises: 
Create Date: 2021-04-13 13:52:28.740080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140b24629ef4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.Column('post_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('comment_user', sa.Integer(), nullable=True),
    sa.Column('comment_post', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_post'], ['blog.id'], ),
    sa.ForeignKeyConstraint(['comment_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_comment')
    op.drop_table('blog')
    # ### end Alembic commands ###
