"""empty message

Revision ID: 70139f99c21b
Revises: 
Create Date: 2021-05-06 19:17:26.884745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70139f99c21b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buy')
    # ### end Alembic commands ###
