"""empty message

Revision ID: ac7b0480144d
Revises: 
Create Date: 2021-05-12 10:44:59.939212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7b0480144d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_pic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pic', sa.String(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_pic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_pic_pic'), ['pic'], unique=False)

    op.create_table('like',
    sa.Column('liker_id', sa.Integer(), nullable=False),
    sa.Column('liked_post_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['liked_post_id'], ['blog.id'], ),
    sa.ForeignKeyConstraint(['liker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('liker_id', 'liked_post_id')
    )
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_column('like')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like', sa.INTEGER(), nullable=True))

    op.drop_table('like')
    with op.batch_alter_table('blog_pic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_pic_pic'))

    op.drop_table('blog_pic')
    # ### end Alembic commands ###
